export const list = [
    {
        id:"fy",
        title:"Forever You",
        title_logo:"./assets/images/fy/fy-logo.svg",
        cover_main:"./assets/images/fy/fy-main.png",
        cover_book:"./assets/images/fy/fy-book.png",
        bgColor:"#131313",
        brandColor:"#DD9F00",
        pageBG:"./assets/images/utss/utss-bg.svg",
        release_date:"Aug. 12, 2023",
        language:"English",
        description:`“Forever You” is a short or "pocket" poetry e-book that contains a collection of romantic poems for your one true love.`,
        highlight_description:"“Maybe you’ll move on from me, but in my papers, we’re still meant to be…”",
        genres:"Poetry, Love",
        words:"600+",
        pages:"20+",
        price:"4.99",
        buy_link:"https://bit.ly/3KCui93",
        sold_out:false,
        reviews:["“Kind, loving, and warm.”",
        "“I LOVED IT!”",
        "“This was a beautiful read.”",
        "“Packs a punch, a good one.”",
        "“I cried, this was so sweet and heartfelt.”",
        "“I know what I'm gifting my wife this coming anniversary.”"],
        mainbook: true
    },
    {
        id:"bdcs",
        title:"Broken Dreams In The City of Stars",
        title_logo:"./assets/images/bdcs/bdcs-logo.svg",
        cover_main:"./assets/images/bdcs/bdcs-main.png",
        cover_book:"./assets/images/bdcs/bdcs-book.png",
        bgColor:"#131313",
        brandColor:"#CA9F75",
        pageBG:"./assets/images/utss/utss-bg.svg",
        release_date:"May 1, 2023",
        language:"English",
        description:`“Broken Dreams In The City of Stars” is an emotional book that explores themes of love, loss, and fate through the perspectives of two characters. Piece together the events of this non-linear short story and follow the intertwined lives of Benjamin and Johnny.`,
        highlight_description:"“Tell me why anything that can rise, must inevitably suffer a fall?”",
        genres:"Poetry, Short Story, Love, Heartbreak",
        words:"4000+",
        pages:"55+",
        price:"9.99",
        buy_link:"https://bit.ly/3oJTJgZ",
        sold_out:false,
        reviews:["“What a story! Incredible!”",
        "“The bitter reality of life, written in the most beautiful of ways.”",
        "“A short story that got me excited.”",
        "“Complex and heartbreaking.”",
        "“It felt like a short film.”",
        "“I know it's a short story, but I want more.”"],
        mainbook: false
    },
    {
        id:"ltwns",
        title:"Letters That Were Never Sent",
        title_logo:"./assets/images/ltwns/ltwns-logo.svg",
        cover_main:"./assets/images/ltwns/ltwns-mob.png",
        cover_book:"./assets/images/ltwns/ltwns-book.png",
        bgColor:"#131313",
        brandColor:"#fff",
        pageBG:"./assets/images/utss/utss-bg.svg",
        release_date:"Jan. 26, 2023",
        language:"English",
        description:`"Letters that were never sent" is a poetry ebook that delves into the many facets of love. From romantic love to self-love and healing, this collection of poems explores the complexities and beauty of one of life's most powerful emotions. Anyone who has ever loved or been in love should read this.`,
        highlight_description:"The poetry ebook for romantic love, self-love, and healing.",
        genres:"Poetry, Romance, Self-love, Healing",
        words:"2000+",
        pages:"50+",
        price:"9.99",
        buy_link:"https://bit.ly/3RcPbKm",
        sold_out:false,
        reviews:["“Powerful impact. This was enjoyable”",
            "“Your poetry speaks to me on levels I never thought possible”",
            "“Phenomenal from start to finish”",
            "“Love love love!”",
            "“Beautiful & Elegant, can’t recommend enough”"],
        mainbook: false
    },
    {
        id:"utss",
        title:"Under The Same Sky",
        title_logo:"./assets/images/utss/utss-logo.png",
        cover_main:"./assets/images/utss/utss-mob.png",
        cover_book:"./assets/images/utss/utss-book.png",
        bgColor:"#131313",
        brandColor:"#fefefe",
        pageBG:"./assets/images/utss/utss-bg.svg",
        release_date:"Nov. 18, 2022",
        language:"English",
        description:`"Under The Same Sky" is a short or "pocket" poetry e-book where the protagonist goes through the pain of separation from their one true love. A collection of poems talking about long distance relationships, trust, love, and heartbreak. `,
        highlight_description:"“How could we be under the same sky, yet we're forced to say goodbye?”",
        genres:"Poetry, Long Distance, Heartbreak, Love",
        words:"1000+",
        pages:"25+",
        price:"4.99",
        buy_link:"https://bit.ly/3ObcMtj",
        sold_out:false,
        reviews:["“I Love it! What a heartbreaking story.”", 
        "“I couldn't stop reading”",
        "“Is there more than 5 stars?”",
        "“This absolutely killed me in the best way possible.”",
        "“I enjoyed it.”",
        "“The words I couldn’t find were right in front of me now. Thank you.”"],
        mainbook: false
    },
    
    
]